
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    networks:
      - sql-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

networks:
  sql-network:
    driver: bridge

volumes:
  mssql-data:
