//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Share.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KarnelTravel.Share.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tải hình ảnh lên cho: {0}..
        /// </summary>
        public static string ERR_MSG_CANNOT_UPLOAD_IMAGE {
            get {
                return ResourceManager.GetString("ERR_MSG_CANNOT_UPLOAD_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã tồn tại - Dữ liệu yêu cầu là duy nhất. .
        /// </summary>
        public static string ERR_MSG_DATA_EXISTED {
            get {
                return ResourceManager.GetString("ERR_MSG_DATA_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu với mã: {0}. Xin kiểm tra lại..
        /// </summary>
        public static string ERR_MSG_DATA_WITH_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_MSG_DATA_WITH_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại dữ liệu.
        /// </summary>
        public static string ERR_MSG_FILE_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERR_MSG_FILE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh: {0} không hợp lệ, nó phải phù hợp với định dạng base64.
        /// </summary>
        public static string ERR_MSG_IMAGE_INVALID_WITH_BASE64 {
            get {
                return ResourceManager.GetString("ERR_MSG_IMAGE_INVALID_WITH_BASE64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh: {0} không hợp lệ, nó không phù hợp với dữ liệu của hình ảnh.
        /// </summary>
        public static string ERR_MSG_IMAGE_INVALID_WITH_BYTE_TYPE {
            get {
                return ResourceManager.GetString("ERR_MSG_IMAGE_INVALID_WITH_BYTE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu không hợp lệ - Yêu cầu là kiểu: {0}.
        /// </summary>
        public static string ERR_MSG_INVALID_DATA_TYPE {
            get {
                return ResourceManager.GetString("ERR_MSG_INVALID_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ. Yêu cầu phải là kiểu dữ liệu Guid. Xin kiểm tra lại..
        /// </summary>
        public static string ERR_MSG_INVALID_GUID_ID {
            get {
                return ResourceManager.GetString("ERR_MSG_INVALID_GUID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu dữ liệu thành công.
        /// </summary>
        public static string INF_MSG_SAVE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("INF_MSG_SAVE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string INF_MSG_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("INF_MSG_SUCCESSFULLY", resourceCulture);
            }
        }


		/// <summary>
		///  Looks up a localized string similar to Không thể sửa đổi dữ liệu.
		/// </summary>
		public static string ERR_MSG_UNABLE_TO_MODIFY_DATA
		{
			get
			{
				return ResourceManager.GetString("ERR_MSG_UNABLE_TO_MODIFY_DATA", resourceCulture);
			}
		}

	}
}
